/* ── Available 3D object shapes for clue representation ── */
export const AVAILABLE_OBJECTS = [
  { id: "chest", name: "Chest (Box)", icon: "📦" },
  { id: "orb", name: "Orb (Sphere)", icon: "🔮" },
  { id: "tome", name: "Tome (Flat Book)", icon: "📖" },
  { id: "lantern", name: "Lantern (Octahedron)", icon: "🏮" },
  { id: "mirror", name: "Mirror (Tall Slab)", icon: "🪞" },
  { id: "diamond", name: "Diamond (Icosahedron)", icon: "💎" },
  { id: "pillar", name: "Pillar (Cylinder)", icon: "🏛️" },
  { id: "crystal", name: "Crystal (Cone)", icon: "🔷" },
];

/* ── 7 Stages — riddle-based escape room puzzles ── */
export const DEFAULT_STAGES = [
  {
    name: "The Awakening",
    answer: "SHADOW",
    question: "I follow you everywhere in daylight yet vanish at night. I copy your every move without sound or weight. What am I?",
    hint: "Think about what sunlight casts on the ground behind you as you walk outdoors.",
    storyline: "You awaken on cold stone, torchlight dancing across the dungeon walls. Two mysterious inscriptions glow on pedestals — each one a fragment of a riddle whispered by the dungeon itself. Solve the riddle to break the first seal!",
    objective: "Collect both riddle clues hidden in the chamber. Walk to the Answer Cart and type the one-word answer.",
    clueCount: 2,
    trashCount: 1,
    theme: { color: 0x00e5ff, emissive: 0x006b80, beacon: 0x00e5ff, label: "#00e5ff" },
    clues: [
      { name: "Dusty Tome", clue: "Riddle Part 1: I am born of light, yet I am dark by nature. I follow you in silence and vanish only in complete darkness.", objectShape: "tome" },
      { name: "Cracked Mirror", clue: "Riddle Part 2: I mimic your every move perfectly, but I am not your reflection. I appear beneath your feet in sunlight. Six letters.", objectShape: "mirror" },
    ],
    trash: [
      { name: "Rotted Barrel", msg: "Just an empty barrel — nothing but disappointment!" },
    ],
    altAnswers: [
      { answer: "FLAME", question: "I dance without feet and breathe without lungs. I consume what I touch yet crave what destroys me. What am I?", clues: [
        { name: "Scorched Plank", clue: "Riddle Part 1: I give light and warmth, yet I will consume anything I touch if given enough time.", objectShape: "crystal" },
        { name: "Ash Tablet", clue: "Riddle Part 2: I dance and flicker but have no body. I live on fuel and die on water. Five letters.", objectShape: "chest" },
      ]},
      { answer: "ECHO", question: "I have no voice, yet I repeat yours. I live in caves and canyons, always the last to speak. What am I?", clues: [
        { name: "Hollow Bell", clue: "Riddle Part 1: Sound travels and bounces off hard surfaces — the returned sound is named after me.", objectShape: "orb" },
        { name: "Cave Inscription", clue: "Riddle Part 2: In Greek myth, a nymph cursed to only repeat others' final words — her name became this phenomenon. Four letters.", objectShape: "pillar" },
      ]},
      { answer: "17", question: "Two enchanted ledgers are hidden in the chamber. Each holds a secret number. Add them together to break the seal. What is the total?", clues: [
        { name: "Worn Ledger", clue: "First Number = 8", objectShape: "tome" },
        { name: "Crystal Flask", clue: "Second Number = 9", objectShape: "orb" },
      ]},
    ],
  },
  {
    name: "The Hourglass Hall",
    answer: "13",
    question: "Three ancient tablets each display an input→output pair. A hidden mathematical rule connects them. Crack the rule and find the output when the input is 6.",
    hint: "Look at each pair carefully: try multiplying the input by 2, then adding 1. Verify it on every pair, then apply it to 6.",
    storyline: "A grand hall stretches before you, lined with countless shattered hourglasses. Three glowing pedestals stand in the gloom — each engraved with a mysterious pair of numbers linked by an arrow. The clock priests sealed this vault with a numeric rule. Only those who can decode the pattern will pass!",
    objective: "Collect all 3 pattern tablets. Each shows \"input → output\". Discover the rule linking them, then calculate the missing output for input 6. Type the number at the Answer Cart.",
    clueCount: 3,
    trashCount: 2,
    theme: { color: 0xbb86fc, emissive: 0x5d4380, beacon: 0xbb86fc, label: "#bb86fc" },
    clues: [
      { name: "Shadow Tablet I",   clue: "Pattern Pair I:   2 → 5",  objectShape: "lantern" },
      { name: "Shadow Tablet II",  clue: "Pattern Pair II:  4 → 9",  objectShape: "orb" },
      { name: "Shadow Tablet III", clue: "Pattern Pair III: 6 → ?",  objectShape: "chest" },
    ],
    trash: [
      { name: "Bone Dust Heap", msg: "Just crumbled bones — nothing useful here, keep searching!" },
      { name: "Empty Potion Vial", msg: "The vial was empty all along — a cruel ruse!" },
    ],
    altAnswers: [
      { answer: "11", question: "Three rune tablets each reveal an input→output pair. Crack the hidden rule, then apply it: what is the output when the input is 5?", clues: [
        { name: "Void Tablet I",   clue: "Pattern Pair I:   1 → 3",  objectShape: "diamond" },
        { name: "Void Tablet II",  clue: "Pattern Pair II:  3 → 7",  objectShape: "crystal" },
        { name: "Void Tablet III", clue: "Pattern Pair III: 5 → ?",  objectShape: "tome" },
      ]},
      { answer: "TIME", question: "I heal all wounds yet cause all scars. No one can see me, touch me, or stop me — yet all are slaves to me. Three clues reveal my name. What am I?", clues: [
        { name: "Shattered Hourglass", clue: "Clue 1: I can be wasted, saved, or spent — but never refilled once gone. Every passing second consumes me.", objectShape: "lantern" },
        { name: "Ancient Clock Face", clue: "Clue 2: Seconds, minutes, and hours are my units. Calendars track me. Historians chronicle me.", objectShape: "orb" },
        { name: "Faded Sundial", clue: "Clue 3: I march forward without pause and wait for no one. I heal wounds — and open others. Four letters: T _ M _", objectShape: "chest" },
      ]},
      { answer: "WIND", question: "You feel me but cannot see me. I move mountains grain by grain. Sailors worship me, trees fear me. Four letters.", clues: [
        { name: "Torn Banner", clue: "Clue 1: I am invisible yet powerful enough to fill sails and uproot ancient trees.", objectShape: "tome" },
        { name: "Rustling Scroll", clue: "Clue 2: I carry seeds, scatter leaves, and shape sand dunes over centuries. You feel me but cannot hold me.", objectShape: "chest" },
        { name: "Weather Vane", clue: "Clue 3: Meteorologists measure my speed and direction. Windmills harvest my energy. Four letters: W _ N _", objectShape: "orb" },
      ]},
    ],
  },
  {
    name: "The Echo Chamber",
    answer: "25",
    question: "Three scorched tablets each show a number and its transformed value. A hidden mathematical rule connects every pair. Find the rule and calculate the transformed value of 5.",
    hint: "Try multiplying each number by itself (squaring it). Check: does 3×3 = 9? Does 4×4 = 16? Then apply the same rule to 5.",
    storyline: "The chamber glows with fierce heat. Three scorched stone tablets are mounted on the walls, each bearing a number and a mysterious result. The formula that links them has been burned away. Only the mathematician who rediscovers it will advance!",
    objective: "Collect all 3 scorched tablets. Each shows \"Number → Secret Value\". Find the mathematical rule, apply it to 5, and type the result at the Answer Cart.",
    clueCount: 3,
    trashCount: 2,
    theme: { color: 0xff7043, emissive: 0x802020, beacon: 0xff7043, label: "#ff7043" },
    clues: [
      { name: "Scorched Tablet I",   clue: "3 → 9",  objectShape: "pillar" },
      { name: "Scorched Tablet II",  clue: "4 → 16", objectShape: "crystal" },
      { name: "Scorched Tablet III", clue: "5 → ?",  objectShape: "diamond" },
    ],
    trash: [
      { name: "Crumbled Rune", msg: "The rune disintegrates on contact — nothing but a decoy!" },
      { name: "False Idol", msg: "The idol was hollow inside — just an elaborate trap!" },
    ],
    altAnswers: [
      { answer: "64", question: "Three scorched tablets each show a number and its secret value. Find the hidden rule — then calculate the secret value for 4.", clues: [
        { name: "Lava Tablet I",   clue: "2 → 8",  objectShape: "diamond" },
        { name: "Lava Tablet II",  clue: "3 → 27", objectShape: "mirror" },
        { name: "Lava Tablet III", clue: "4 → ?",  objectShape: "chest" },
      ]},
      { answer: "SILENCE", question: "I can be shattered with a single word, yet no one can hold me. The more you keep of me, the more powerful I become. Libraries and tombs are full of me. What am I?", clues: [
        { name: "Stone Paradox I", clue: "Clue 1: I can be broken without being touched. Even whispering a single word aloud will shatter me completely.", objectShape: "pillar" },
        { name: "Stone Paradox II", clue: "Clue 2: The more of me you keep, the louder I seem to grow. Libraries and sacred tombs are filled with me.", objectShape: "crystal" },
        { name: "Stone Paradox III", clue: "Clue 3: I am the absence of something, yet I am powerful enough to speak volumes. Seven letters: S _ L _ N _ _", objectShape: "diamond" },
      ]},
      { answer: "MIRROR", question: "I show your face but reverse left and right. I tell the truth yet always deceive. What am I?", clues: [
        { name: "Polished Slab", clue: "Clue 1: I reflect you perfectly — except I always reverse left and right to create your opposite.", objectShape: "mirror" },
        { name: "Silver Fragment", clue: "Clue 2: Narcissus fell in love not with himself but with what he saw when he gazed into me.", objectShape: "orb" },
        { name: "Reflection Rune", clue: "Clue 3: I show you yourself, reversed. Found in still water, polished glass, silver surfaces. Six letters: M _ R _ O _", objectShape: "diamond" },
      ]},
    ],
  },
  {
    name: "The Radiologist's Vault",
    answer: "DICOM",
    question: "Five illuminated panels each carry one letter of the universal medical imaging standard. Arrange all five letters in order (1→5) to spell the name of the standard used by every CT scanner, MRI machine, X-ray system, and PACS in modern healthcare.",
    hint: "D = Digital, I = Imaging, C = Communications, O = Of, M = Medicine. This is the standard that replaced film and connected every scanner to every screen since the 1990s.",
    storyline: "Backlit panels line the walls — ghostly CT slices, MRI cross-sections, X-ray silhouettes of unknown anatomy. You have entered the Radiologist's Vault. Five panels glow with a single letter each. Together they spell the universal standard that transformed modern medicine by replacing physical film with digital data and connecting every imaging device to every workstation on the planet.",
    objective: "Collect all 5 letter panels in order. Each reveals one letter of the 5-letter medical imaging standard. Arrange them and submit the answer at the cart.",
    clueCount: 5,
    trashCount: 3,
    theme: { color: 0x448aff, emissive: 0x1a3680, beacon: 0x448aff, label: "#448aff" },
    clues: [
      { name: "Panel 1 — D", clue: "Letter 1 of 5: 'D' — stands for Digital. Modern radiology abandoned film for ___ital storage and transmission.", objectShape: "tome" },
      { name: "Panel 2 — I", clue: "Letter 2 of 5: 'I' — stands for Imaging. CT, MRI, PET, ultrasound, and X-ray are all forms of medical ___aging.", objectShape: "orb" },
      { name: "Panel 3 — C", clue: "Letter 3 of 5: 'C' — stands for Communications. This standard defines ___ommunications between scanners, PACS servers, and radiologist workstations.", objectShape: "chest" },
      { name: "Panel 4 — O", clue: "Letter 4 of 5: 'O' — stands for Of. A two-letter bridge in the full name: 'Digital Imaging and Communications ___ Medicine'.", objectShape: "lantern" },
      { name: "Panel 5 — M", clue: "Letter 5 of 5: 'M' — stands for Medicine. The field that created and depends entirely on this imaging standard.", objectShape: "diamond" },
    ],
    trash: [
      { name: "Corrupt Tag (FFFF,FFFF)", msg: "Tag (FFFF,FFFF) — undefined private attribute! This DICOM tag is corrupt and completely useless!" },
      { name: "Empty DICOM Series", msg: "Zero images in this series — a phantom dataset! There is nothing to retrieve here!" },
      { name: "Broken PACS Link", msg: "Connection refused — the PACS node is offline! A complete diagnostic dead end!" },
    ],
    altAnswers: [
      { answer: "HIPAA", question: "Five panels reveal one letter each of a landmark US healthcare privacy law enacted in 1996. Arrange them to spell the 5-letter acronym.", clues: [
        { name: "Shield Plaque H", clue: "Letter 1 of 5: 'H' — stands for Health. The ___ Insurance Portability and Accountability Act governs patient data.", objectShape: "pillar" },
        { name: "Shield Plaque I", clue: "Letter 2 of 5: 'I' — stands for Insurance. Health ___ Portability — you can keep coverage when changing employers.", objectShape: "crystal" },
        { name: "Shield Plaque P", clue: "Letter 3 of 5: 'P' — stands for Portability. Health Insurance ___ — your coverage travels with you.", objectShape: "mirror" },
        { name: "Shield Plaque A", clue: "Letter 4 of 5: 'A' — stands for Accountability. ___ means those who misuse patient data can be audited and penalised.", objectShape: "tome" },
        { name: "Shield Plaque A2", clue: "Letter 5 of 5: 'A' — stands for Act. This is a US federal law — the Health Insurance Portability and Accountability ___.", objectShape: "chest" },
      ]},
      { answer: "PACS", question: "Four panels reveal the letters of the system radiologists use daily to store, retrieve, and view medical images. Spell the 4-letter acronym.", clues: [
        { name: "Archive Tile P", clue: "Letter 1 of 4: 'P' — stands for Picture. A ___ Archiving and Communication System stores every DICOM image.", objectShape: "orb" },
        { name: "Archive Tile A", clue: "Letter 2 of 4: 'A' — stands for Archiving. Picture ___ — long-term storage of millions of medical images.", objectShape: "lantern" },
        { name: "Archive Tile C", clue: "Letter 3 of 4: 'C' — stands for Communication. Picture Archiving and ___ — transmitting images to radiologists.", objectShape: "diamond" },
        { name: "Archive Tile S", clue: "Letter 4 of 4: 'S' — stands for System. Picture Archiving and Communication ___ — the complete infrastructure.", objectShape: "pillar" },
      ]},
      { answer: "32", question: "Five signal panels each show one term in a doubling sequence. Starting from 1, each term is double the previous. What is the 5th term?", clues: [
        { name: "Signal Panel I",   clue: "Term 1: 1", objectShape: "pillar" },
        { name: "Signal Panel II",  clue: "Term 2: 2  (1 × 2)", objectShape: "crystal" },
        { name: "Signal Panel III", clue: "Term 3: 4  (2 × 2)", objectShape: "mirror" },
        { name: "Signal Panel IV",  clue: "Term 4: 8  (4 × 2)", objectShape: "orb" },
        { name: "Signal Panel V",   clue: "Term 5: ?  (double Term 4)", objectShape: "chest" },
      ]},
    ],
  },
  {
    name: "The Protocol Ward",
    answer: "MSH",
    question: "In every HL7 version 2 message, one three-letter segment always appears first. It defines the message type, the sending application, the receiving system, and the field separator. Collect all clues and name this mandatory segment.",
    hint: "It stands for Message Segment Header. Every HL7 v2 clinical message — ADT, ORM, ORU — begins with this segment, and its second field is always the pipe character '|'.",
    storyline: "Pipe-delimited text scrolls across every wall — a torrent of clinical transactions in the ancient language of HL7 v2. ADT^A01, ORM^O01, ORU^R01 flash past in endless streams. You can see PID, OBR, OBX, NTE segments everywhere — but one three-letter code appears at the very beginning of every single message without exception.",
    objective: "Collect all 3 HL7 clues. Each reveals something about the first and most important segment of every HL7 v2 message. Submit the 3-letter segment name at the Answer Cart.",
    clueCount: 3,
    trashCount: 3,
    theme: { color: 0x69f0ae, emissive: 0x1a5c35, beacon: 0x69f0ae, label: "#69f0ae" },
    clues: [
      { name: "Pipe Scroll", clue: "Clue 1: In HL7 v2, I am the first segment of every message. My second field is always '|' — the field separator that defines how every subsequent field in the message is parsed.", objectShape: "tome" },
      { name: "System Notice", clue: "Clue 2: I carry Sending Application (field 3), Sending Facility (field 4), Receiving Application (field 5), Message Type (field 9), and Message Control ID (field 10). Without me, no HL7 message can be processed.", objectShape: "orb" },
      { name: "Header Rune", clue: "Clue 3: My three letters — M, S, H — abbreviate my full name: Message Segment Header. I am the mandatory first segment in every HL7 v2 clinical transaction ever sent.", objectShape: "chest" },
    ],
    trash: [
      { name: "Orphaned OBX Segment", msg: "An OBX with no parent OBR — this HL7 message is malformed and will be rejected! A diagnostic dead end!" },
      { name: "Z-Segment Fragment", msg: "A Z-segment — a local, non-standard HL7 extension. No universal meaning here, just site-specific confusion!" },
      { name: "Rejected ACK", msg: "ACK|AE — Application Error! The receiving system rejected this message outright. Nothing useful here!" },
    ],
    altAnswers: [
      { answer: "PID", question: "This HL7 v2 segment carries the patient's name, date of birth, medical record number, and address. It is the backbone of every ADT message. Name the 3-letter segment.", clues: [
        { name: "Patient Ledger", clue: "Clue 1: I hold the Patient Identifier List (field 3), Patient Name (field 5), and Date of Birth (field 7). I define exactly who every HL7 message is about.", objectShape: "pillar" },
        { name: "Identity Scroll", clue: "Clue 2: In an ADT^A01 Admit message, I follow MSH and EVN. Without me, the patient has no identity in the receiving system.", objectShape: "crystal" },
        { name: "Registry Mark", clue: "Clue 3: My three letters — P, I, D — stand for Patient Identification. I am the most referenced segment across all HL7 v2 message types.", objectShape: "diamond" },
      ]},
      { answer: "OBX", question: "This HL7 v2 segment carries individual observation results — lab values, vital signs, and radiology findings. Each result gets its own instance. Name the 3-letter segment.", clues: [
        { name: "Lab Result Tile", clue: "Clue 1: I carry a single observation — a glucose level, a blood pressure reading, or a pathology finding. One result, one me.", objectShape: "mirror" },
        { name: "Result Scroll", clue: "Clue 2: My fields include Observation Identifier (field 3), Observation Value (field 5), and Units (field 6). I follow OBR segments in laboratory ORU^R01 messages.", objectShape: "tome" },
        { name: "Value Rune", clue: "Clue 3: My three letters — O, B, X — stand for Observation. I am the segment that delivers the actual clinical measurement data in every HL7 results message.", objectShape: "lantern" },
      ]},
      { answer: "10", question: "Three number stones reveal the first three triangular numbers (the sum of consecutive integers). Find the pattern and give the 4th triangular number.", clues: [
        { name: "Triangle Stone I",   clue: "T(1) = 1   (sum of 1)", objectShape: "pillar" },
        { name: "Triangle Stone II",  clue: "T(2) = 3   (sum of 1+2)", objectShape: "crystal" },
        { name: "Triangle Stone III", clue: "T(3) = 6   (sum of 1+2+3) → T(4) = ?  (sum of 1+2+3+4)", objectShape: "diamond" },
      ]},
    ],
  },
  {
    name: "The Cartographer's Room",
    answer: "WEST",
    question: "Follow the compass directions listed in your clues — in order. You start facing NORTH. After all three turns, what direction are you facing? (NORTH / EAST / SOUTH / WEST)",
    hint: "Face NORTH. Each turn rotates you exactly 90°: RIGHT = clockwise (N→E→S→W), LEFT = counter-clockwise (N→W→S→E).",
    storyline: "Ancient maps cover every wall — charts of lost continents, forgotten sea lanes, kingdoms erased by time. A compass rose is carved deep into the floor and four glowing direction stones form a trail. Only the navigator who follows each bearing precisely will find the way to the next chamber.",
    objective: "Collect all 4 direction clues. Follow each 90° turn starting from NORTH. Submit the final compass bearing you are facing at the Answer Cart.",
    clueCount: 4,
    trashCount: 3,
    theme: { color: 0xffab00, emissive: 0x805500, beacon: 0xffab00, label: "#ffab00" },
    clues: [
      { name: "Compass Rose", clue: "You start facing NORTH", objectShape: "chest" },
      { name: "Wind Vane I", clue: "First turn: RIGHT", objectShape: "orb" },
      { name: "Sun Dial II", clue: "Second turn: RIGHT", objectShape: "tome" },
      { name: "Sky Chart III", clue: "Third turn: RIGHT", objectShape: "lantern" },
    ],
    trash: [
      { name: "Fool's Compass", msg: "The needle spins wildly — this compass is cursed! Completely unreliable!" },
      { name: "Torn Navigation Chart", msg: "The chart crumbles to dust in your hands — it was nothing but a decoy!" },
      { name: "Hollow Lodestone", msg: "The lodestone is hollow and has no magnetic properties whatsoever — just an elaborate trick!" },
    ],
    altAnswers: [
      { answer: "EAST", question: "Follow the compass directions in your clues, starting NORTH. After all three turns, what direction are you facing?", clues: [
        { name: "Bearing Stone", clue: "You start facing NORTH", objectShape: "diamond" },
        { name: "Course Rune I", clue: "First turn: RIGHT", objectShape: "mirror" },
        { name: "Course Rune II", clue: "Second turn: LEFT", objectShape: "crystal" },
        { name: "Course Rune III", clue: "Third turn: RIGHT", objectShape: "pillar" },
      ]},
      { answer: "SOUTH", question: "Follow the compass directions in your clues, starting NORTH. After all three turns, what direction are you facing?", clues: [
        { name: "Astrolabe", clue: "You start facing NORTH", objectShape: "chest" },
        { name: "Heading Slab I", clue: "First turn: RIGHT", objectShape: "orb" },
        { name: "Heading Slab II", clue: "Second turn: RIGHT", objectShape: "chest" },
        { name: "Heading Slab III", clue: "Third turn: LEFT", objectShape: "tome" },
      ]},
      { answer: "26", question: "Four number tablets each show an input→output pair. Crack the hidden rule, then apply it: what is the output when the input is 7?", clues: [
        { name: "Number Compass I",  clue: "Pair I:  1 → 2   (rule: multiply by 4, then subtract 2)", objectShape: "chest" },
        { name: "Number Compass II", clue: "Pair II: 2 → 6   (confirm: 2×4−2 = 6)", objectShape: "orb" },
        { name: "Number Compass III",clue: "Pair III: 3 → 10  (confirm: 3×4−2 = 10)", objectShape: "tome" },
        { name: "Number Compass IV", clue: "Pair IV:  7 → ?   (apply the rule to 7)", objectShape: "lantern" },
      ]},
    ],
  },
  {
    name: "The Revelation",
    answer: "RELIC",
    question: "Five rune stones each hold one encoded letter. The ancient cipher shifts every letter FORWARD 3 positions (A→D, B→E … Z→C). Decode the 5-letter word by shifting each letter BACK 3.",
    hint: "Reverse the shift: subtract 3 from each letter's alphabet position. U→R, H→E, O→L, L→I, F→C. The decoded word is an ancient artefact.",
    storyline: "The final chamber blazes with emerald light. Five encoded letters are carved into towering stone pillars — sealed by the cipher of the ancients, which advances every letter by three positions. Only by reversing the shift will the great vault unseal and your escape from the dungeon be complete forever.",
    objective: "Collect all 5 rune stones. Each shows one encoded letter. Shift each letter BACK by 3 to decode it, then submit the 5-letter word at the Answer Cart.",
    clueCount: 5,
    trashCount: 3,
    theme: { color: 0x00e676, emissive: 0x00733b, beacon: 0x00e676, label: "#00e676" },
    clues: [
      { name: "Verdant Rune I",   clue: "Encoded letter 1: U", objectShape: "tome" },
      { name: "Verdant Rune II",  clue: "Encoded letter 2: H", objectShape: "orb" },
      { name: "Verdant Rune III", clue: "Encoded letter 3: O", objectShape: "lantern" },
      { name: "Verdant Rune IV",  clue: "Encoded letter 4: L", objectShape: "chest" },
      { name: "Verdant Rune V",   clue: "Encoded letter 5: F", objectShape: "diamond" },
    ],
    trash: [
      { name: "Dead Root", msg: "The root withers in your hands… cursed garbage!" },
      { name: "Withered Leaf", msg: "The leaf crumbles to nothing… a trap!" },
      { name: "Hollow Bark", msg: "The bark is hollow and rotten… just worthless junk!" },
    ],
    altAnswers: [
      { answer: "FLAME", question: "Five rune stones, each encoded. Shift each letter BACK 3 to reveal the hidden 5-letter word.", clues: [
        { name: "Ember Glyph I",   clue: "Encoded letter 1: I", objectShape: "orb" },
        { name: "Ember Glyph II",  clue: "Encoded letter 2: O", objectShape: "chest" },
        { name: "Ember Glyph III", clue: "Encoded letter 3: D", objectShape: "pillar" },
        { name: "Ember Glyph IV",  clue: "Encoded letter 4: P", objectShape: "diamond" },
        { name: "Ember Glyph V",   clue: "Encoded letter 5: H", objectShape: "crystal" },
      ]},
      { answer: "STONE", question: "Five rune stones, each encoded. Shift each letter BACK 3 to reveal the hidden 5-letter word.", clues: [
        { name: "Rock Cipher I",   clue: "Encoded letter 1: V", objectShape: "mirror" },
        { name: "Rock Cipher II",  clue: "Encoded letter 2: W", objectShape: "tome" },
        { name: "Rock Cipher III", clue: "Encoded letter 3: R", objectShape: "orb" },
        { name: "Rock Cipher IV",  clue: "Encoded letter 4: Q", objectShape: "chest" },
        { name: "Rock Cipher V",   clue: "Encoded letter 5: H", objectShape: "lantern" },
      ]},
      { answer: "8", question: "Five rune stones each reveal one number in the sacred Fibonacci sequence, where each term is the sum of the two before it. What is the next number after the 5th term?", clues: [
        { name: "Fib Rune I",   clue: "Term 1: 1", objectShape: "tome" },
        { name: "Fib Rune II",  clue: "Term 2: 1", objectShape: "orb" },
        { name: "Fib Rune III", clue: "Term 3: 2  (1+1)", objectShape: "lantern" },
        { name: "Fib Rune IV",  clue: "Term 4: 3  (1+2)", objectShape: "chest" },
        { name: "Fib Rune V",   clue: "Term 5: 5  (2+3) → Term 6 = ?  (3+5)", objectShape: "diamond" },
      ]},
    ],
  },
];
